# Copyright (C) 2026 Nye Liu
# SPDX-License-Identifier: GPL-3.0-or-later
# Sample proxy fragment. Not a full vhost.
# ProxyPass / http://127.0.0.1:8080/
# ProxyPassReverse / http://127.0.0.1:8080/
# ProxyPreserveHost On
# LimitRequestBody 33554432
# Set PUBLIC_URL to the browser URL. bootstashd does not read X-Forwarded-*.
