# Copyright (C) 2026 Nye Liu
# SPDX-License-Identifier: GPL-3.0-or-later

# Sample vhost
# Requires: a2enmod proxy proxy_http
<VirtualHost *:443>
    # Assumes PUBLIC_URL=https://bootstash.example.com
    # bootstashd does not read X-Forwarded-*.
    ServerName bootstash.example.com
    # ServerAlias bs.example.com  # will not work, make a separate vhost
    ServerAdmin admin@example.com

    # Assumes TLS=no in /etc/default/bootstash
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/
    ProxyPreserveHost On
    LimitRequestBody 33554432
</VirtualHost>

# Extra DNS name: Redirect only. Do not ProxyPass. PUBLIC_URL is ServerName above.
<VirtualHost *:443>
    ServerName bs.example.com
    Redirect permanent / https://bootstash.example.com/
</VirtualHost>
