# Copyright (C) 2026 Nye Liu
# SPDX-License-Identifier: GPL-3.0-or-later
# Sample proxy fragment. Not a full vhost.
# ProxyPass / http://127.0.0.1:8080/
# ProxyPassReverse / http://127.0.0.1:8080/
# RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
# RequestHeader set X-Forwarded-Host "%{HTTP_HOST}e"
# LimitRequestBody 33554432
