#!/usr/bin/env python3
# Copyright (C) 2026 Nye Liu
# SPDX-License-Identifier: GPL-3.0-or-later
"""Refresh the generated Go-module list in debian/copyright."""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

BEGIN = "# BEGIN GO-MODULES"
END = "# END GO-MODULES"
COPYRIGHT = Path("debian/copyright")


def classify(text: str) -> str:
    if re.search(r"SPDX-License-Identifier:\s*(\S+)", text):
        return re.search(r"SPDX-License-Identifier:\s*(\S+)", text).group(1)
    if "Apache License" in text and "Version 2.0" in text:
        return "Apache-2.0"
    if "Redistribution and use" in text:
        if re.search(r"neither the name|endorse", text, re.I):
            return "BSD-3-clause"
        return "BSD-2-clause"
    if "Permission is hereby granted, free of charge" in text:
        return "MIT"
    raise SystemExit("unrecognized license text")


def license_file(moddir: Path) -> Path:
    for name in ("LICENSE", "LICENSE.md", "LICENCE", "COPYING", "COPYING.md"):
        p = moddir / name
        if p.is_file():
            return p
    matches = sorted(moddir.glob("LICENSE*")) + sorted(moddir.glob("COPYING*"))
    if matches:
        return matches[0]
    raise SystemExit(f"no license file in {moddir}")


def modules() -> list[tuple[str, str, str]]:
    subprocess.check_call(["go", "mod", "download"], stdout=subprocess.DEVNULL)
    env = os.environ.copy()
    env["CGO_ENABLED"] = "1"
    out = subprocess.check_output(
        [
            "go",
            "list",
            "-deps",
            "-f",
            "{{if and .Module (not .Module.Main)}}{{.Module.Path}}\t{{.Module.Version}}\t{{.Module.Dir}}{{end}}",
            "./cmd/bootstashd",
            "./cmd/bootstash",
        ],
        env=env,
        text=True,
    )
    seen: dict[str, tuple[str, str]] = {}
    for line in out.splitlines():
        if not line.strip():
            continue
        path, ver, directory = line.split("\t")
        if not directory:
            subprocess.check_call(["go", "mod", "download", f"{path}@{ver}"])
            directory = subprocess.check_output(
                ["go", "list", "-m", "-f", "{{.Dir}}", f"{path}@{ver}"],
                text=True,
            ).strip()
        lic = classify(license_file(Path(directory)).read_text(errors="replace"))
        seen[path] = (ver, lic)
    return [(p, seen[p][0], seen[p][1]) for p in sorted(seen)]


def block(rows: list[tuple[str, str, str]]) -> str:
    lines = [
        BEGIN,
        "# Regenerated by `make copyright`. Do not edit this block.",
        "Comment: The binaries link these Go modules (not vendored):",
    ]
    for path, ver, lic in rows:
        lines.append(f" {path} {ver} {lic}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def main() -> int:
    text = COPYRIGHT.read_text()
    if BEGIN not in text or END not in text:
        print(f"{COPYRIGHT}: missing {BEGIN} / {END} markers", file=sys.stderr)
        return 1
    new = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
        block(modules()),
        text,
        count=1,
        flags=re.S,
    )
    if new != text:
        COPYRIGHT.write_text(new)
        print(f"updated {COPYRIGHT}")
    else:
        print(f"{COPYRIGHT} already current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
